-- drop table Birthday_Age;
drop table VIP;
drop table SecurityInfo_Of;
drop table Ban;
drop table Admin_Monitor;
drop table Subscribe;
drop table About;
drop table Comment_Create_Follows;
drop table BID;
drop table UID_CID_DATETIME;
drop table CID_DATETIME_Title;
drop table Topic;
drop table Blog_Users;
drop table Community;
-- select table_name from user_tables;